pipeline {
    agent any
    stages {
        stage("build"){
            steps{
                 script{
                     try {
                         sh 'docker rmi front-unit'
                     } catch (e) {
                         sh 'echo "fail remove test-images"'
                     }
                 }
                 //sh 'sudo docker exec -it jenkins bash'
                 sh 'cp /etc/nginx/sites-available/default ./Front/theme'
                 sh 'docker build -t front-unit -f Front/DockFile.e2e ./Front/theme'
                 sh 'sudo docker run front-unit npm run test'
             }
             post {
                 success{
                     sh 'echo unit 테스트 성공'
                 }
                 failure{
                     sh 'echo unit 테스트 실패'
                 }
             }
        }
    }    
}
