pipeline {
    agent any
    stages {
        stage("build"){
            steps{
                 script{
                     try {
                         sh 'docker rmi front-unit'
                     } catch (e) {
                         sh 'echo "fail remove test-images"'
                     }
                 }
                 sh 'docker build -t front-unit -f Front/DockerFile.e2e ./Front'
                 // sh 'docker run front-test npm run test'
             }
             post {
                 success{
                     sh 'echo unit 테스트 성공'
                 }
                 failure{
                     sh 'echo unit 테스트 실패'
                 }
             }
        }
    }    
}
